# Generated by Django 4.1.7 on 2023-03-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0002_event_user_role_ticket_review_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
