# Generated by Django 4.1.7 on 2023-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0006_remove_ticket_status_event_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateField(default="0000-00-00"),
        ),
    ]
