# Generated by Django 4.1.7 on 2023-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0007_alter_event_registration_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="images",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
