# Generated by Django 4.1.7 on 2023-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0009_alter_event_registration_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateField(default=None),
        ),
    ]
