# Generated by Django 4.1.7 on 2023-03-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0012_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field = models.CharField(max_length=255, default="default.png") 
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.IntegerField(default=None),
        ),
    ]
