# Generated by Django 4.1.7 on 2023-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0014_user_unique_name_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="state",
            field = models.CharField(max_length=20, default="open") 
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
    ]
