# Generated by Django 4.1.7 on 2023-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0015_remove_event_state_remove_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateField(),
        ),
    ]
