# Generated by Django 4.1.7 on 2023-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0016_alter_event_registration_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("images", models.CharField(default="", max_length=1000)),
                ("item_type", models.CharField(max_length=50)),
                ("timestamp", models.TimeField()),
            ],
        ),
    ]
