# Generated by Django 4.1.7 on 2023-03-26 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0017_discussion"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="front.user",
            ),
        ),
    ]
