# Generated by Django 4.1.7 on 2023-03-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0019_discussion_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front.discussion",
            ),
        ),
    ]
