# Generated by Django 4.1.7 on 2023-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0020_alter_discussion_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
