# Generated by Django 4.1.7 on 2023-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0021_alter_discussion_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="images",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="title",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
