# Generated by Django 4.1.7 on 2023-03-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0022_alter_discussion_images_alter_discussion_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="event",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="front.event",
            ),
        ),
    ]
