# Generated by Django 4.1.7 on 2023-04-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0024_alter_discussion_user_views_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.CharField(default="f", max_length=50),
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="front.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="front.user",
                    ),
                ),
            ],
        ),
    ]
